GET http://localhost:3005/animeWordle/searchcharacter/L

###

GET http://localhost:3005/animeWordle/guesscharacter/Edward%20ELRIC

###

GET https://animewordle.herokuapp.com/animeWordle/guesscharacter/Naruto%20UZUMAKI/4

###

GET https://animewordle.herokuapp.com/animeWordle/searchcharacter/L

###

GET https://animewordle.herokuapp.com/animeWordle/guessanime/bleach

###

GET https://animewordle.herokuapp.com/animeWordle/oftheday/character